name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '3.13.9'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.0
  chopper: ^7.0.9
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  get_it: ^7.6.4
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mockito: ^5.4.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  json_serializable: ^6.7.1
  flutter_gen_runner:
  flutter_lints: ^3.0.1

flutter_gen:
  output: lib/gen/
  line_length: 100

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/weather/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg"
  adaptive_icon_background: "#FF7e57c2"

flutter_native_splash:
  color: "#7e57c2"